import urllib as url
import json
from sqlalchemy import Table,Column,Float, String,MetaData,Integer
from sqlalchemy.dialects.postgresql import ARRAY
from geoalchemy import *

placesApiKey='AIzaSyAvfYLzTvK9xfIzwRMkWifY_WZqQpFQsVw'
baseUrl="https://maps.googleapis.com/maps/api/place/textsearch/json?query=%s"
queryUrlString="%s+in+%s&type=%s&sensor=false&key=%s"

states=['California','Oregon','Washington','Idaho','Montana']
allowTypes=['establishment']
gKeywords={'wood mill':['lumber','mill','sawmill','pulp']}

metadata=MetaData()
woodUsers= Table('g_query_wood', metadata,
                 Column('id', Integer, primary_key=True),
                 Column('name', String),
                 GeometryColumn('geom', Point(2)),
                 Column('type', ARRAY(String)),
                 COlumn('json',String))

for st in states:
    queryString=queryUrlString%('+'.join([i for i in gKeywords['wood mill']]), st,'+'.join([i for i in allowTypes]),placesApiKey)
    js=json.loads(url.urlopen(baseUrl%queryString).read())
    
    for resPage in range(1,21):
        
    
    nextPage=baseUrl%queryString
    print baseUrl%queryString
    
                                
types={'accounting':False ,
        'airport':False ,
        'amusement_park':False ,
        'aquarium':False ,
        'art_gallery':False ,
        'atm':False ,
        'bakery':False ,
        'bank':False ,
        'bar':False ,
	'beauty_salon':False ,
	'bicycle_store':False ,
	'book_store':False ,
	'bowling_alley':False ,
	'bus_station':False ,
	'cafe':False ,
	'campground':False ,
	'car_dealer':False ,
	'car_rental':False ,
	'car_repair':False ,
	'car_wash':False ,
	'casino':False ,
	'cemetery':False ,
	'church':False ,
	'city_hall':False ,
	'clothing_store':False ,
	'convenience_store':False ,
	'courthouse':False ,
	'dentist':False ,
	'department_store':False ,
	'doctor':False ,
	'electrician':False ,
	'electronics_store':False ,
	'embassy':False ,
	'establishment':False ,
	'finance':False ,
	'fire_station':False ,
	'florist':False ,
	'food':False ,
	'funeral_home':False ,
	'furniture_store':False ,
	'gas_station':False ,
	'general_contractor':False ,
	'grocery_or_supermarket':False ,
	'gym':False ,
	'hair_care':False ,
	'hardware_store':False ,
	'health':False ,
	'hindu_temple':False ,
	'home_goods_store':False ,
	'hospital':False ,
	'insurance_agency':False ,
	'jewelry_store':False ,
	'laundry':False ,
	'lawyer':False ,
	'library':False ,
	'liquor_store':False ,
	'local_government_office':False ,
	'locksmith':False ,
	'lodging':False ,
	'meal_delivery':False ,
	'meal_takeaway':False ,
	'mosque':False ,
	'movie_rental':False ,
	'movie_theater':False ,
	'moving_company':False ,
	'museum':False ,
	'night_club':False ,
	'painter':False ,
	'park':False ,
	'parking':False ,
	'pet_store':False ,
	'pharmacy':False ,
	'physiotherapist':False ,
	'place_of_worship':False ,
	'plumber':False ,
	'police':False ,
	'post_office':False ,
	'real_estate_agency':False ,
	'restaurant':False ,
	'roofing_contractor':False ,
	'rv_park':False ,
	'school':False ,
	'shoe_store':False ,
	'shopping_mall':False ,
	'spa':False ,
	'stadium':False ,
	'storage':False ,
	'store':False ,
	'subway_station':False ,
	'synagogue':False ,
	'taxi_stand':False ,
	'train_station':False ,
	'travel_agency':False ,
	'university':False ,
	'veterinary_care':False ,
	'zoo':False ,
	'administrative_area_level_1':False ,
	'administrative_area_level_2':False ,
	'administrative_area_level_3':False ,
	'colloquial_area':False ,
	'country':False ,
	'floor':False ,
	'geocode':False ,
	'intersection':False ,
	'locality':False ,
	'natural_feature':False ,
	'neighborhood':False ,
	'political':False ,
	'point_of_interest':False ,
	'post_box':False ,
	'postal_code':False ,
	'postal_code_prefix':False ,
	'postal_town':False ,
	'premise':False ,
	'room':False ,
	'route':False ,
	'street_address':False ,
	'street_number':False ,
	'sublocality':False ,
	'sublocality_level_4':False ,
	'sublocality_level_5':False ,
	'sublocality_level_3':False ,
	'sublocality_level_2':False ,
	'sublocality_level_1':False ,
	'subpremise':False ,
	'transit_station':False}
